### ISSUE TITLE
Listener or Option to check current page URL

### ISSUE THREAD

**Issue by bhekor** [Cap-go/capacitor-inappbrowser#55] opened 2023-06-28 11:42 UTC
Please can you add a listener to check the current page URL and perform a function like closing the browser etc?

In the case where someone needs to perform an action on the action web and when done close the browser automatically instead of waiting for the user to close the page manually.

Thanks in advance.

**Comment by riderx** [comment] 2023-07-06 14:56
Hey you already have this with [addListener('urlChangeEvent', ...)](https://github.com/Cap-go/capacitor-inappbrowser#addlistenerurlchangeevent)
and the close method :)

**Comment by Senzo13** [comment] 2023-10-03 12:10
Hello, after having opened a url, I cannot retrieve it via open and addEventListerner, it does not listen to anything, even when I change the url via this same webView, so I cannot move forward on my code, does anyone have a working code example somewhere for this?

**Comment by mohanmuthusamy** [comment] 2023-10-04 06:35
@bhekor, the event listener will work only on openWebView, but I tried the event is triggering, but when I close the browser, it closes the entire app and show an error in the console
**Caused by: java.lang.Throwable: A WebView method was called on thread 'CapacitorPlugins'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {b5b07c7} called on Looper (CapacitorPlugins, tid 91) {153e440}, FYI main Looper is Looper (main, tid 2) {b5b07c7})**

**Comment by riderx** [comment] 2023-10-05 16:52
the close issue was something different, i just made a fix for it !
@bhekor what method do you use to open ''openWebView'' ?
Because the open one don't have the event

**Comment by adele2014** [comment] 2024-01-23 12:37
Thanks for this plugin @riderx . I have  a similar issue on Android. The urlChangeEvent is not listening to a url redirect even when using openWebView. What can I do.

**Comment by GuillaumeUnice** [comment] 2024-01-23 16:06
Same issue on my side

**Comment by riderx** [comment] 2024-01-23 20:58
Do you use the last version of the plugin ?
Can any of you provide a reproduction repo ?

**Comment by GuillaumeUnice** [comment] 2024-01-24 08:58
Ok with the last version and using openWebView it's working on my side

**Comment by beliven-davide-lorigliola** [comment] 2024-02-26 20:15
Hi there!

I can confirm that on Android listening to "onChangeUrl" me toot I get app closing/crashing on WebView close:

```
Caused by: java.lang.Throwable: A WebView method was called on thread 'CapacitorPlugins'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {b5b07c7} called on Looper (CapacitorPlugins, tid 91) {153e440}, FYI main Looper is Looper (main, tid 2) {b5b07c7})

```

**Closed** 2024-03-02 00:40 UTC
